spring:
  profiles:
    active: local # 기보 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

  # dev-tools for hot-reloading
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include:
  - real-db

spring:
  profiles: set1
server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include:
  - real-db

spring:
  profiles: set2
server:
  port: 8082