spring:
  profiles:
    active: local # 기보 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

  # dev-tools for hot-reloading
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true
