---
spring:
  profiles: set1
server:
  port: 8081

---
spring:
  profiles: set2
server:
  port: 8082

---
spring:
  profiles: real-db
  datasource:
    url: jdbc:mariadb://springbootwebservice.ci0kc602diiq.ap-northeast-2.rds.amazonaws.com/webservice
    username: cybermed
    password: cyber3970
    driver-class-name: org.mariadb.jdbc.Driver
